//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string DODGERIGHT = "dodgeright";
        
        public const string DODGELEFT = "dodgeleft";
        
        public const string ULTIMATE = "ultimate";
        
        public const string RIGHTHIT = "righthit";
        
        public const string LEFTTHIT = "leftthit";
        
        public const string ENOMYHIT = "enomyhit";
    }
}
